CREATE SCHEMA SMART_ROUTES;

USE SMART_ROUTES;

CREATE TABLE PARADA(
	ID_PARADA	INTEGER PRIMARY KEY AUTO_INCREMENT,
	LUGAR		VARCHAR(50),
    POSICION	INTEGER
);

CREATE TABLE PARADAMEDIA(
	ID_PARADA_M	INTEGER PRIMARY KEY AUTO_INCREMENT,
	LUGAR		VARCHAR(50),
    VIAJE		INTEGER,
    POSICION	INTEGER
);

CREATE TABLE HORARIO(
	ID_HORARIO	INTEGER PRIMARY KEY AUTO_INCREMENT,
    HORA_SALIDA	DATETIME,
    HORA_LLEGAD	DATETIME
);

CREATE TABLE BUS(
	ID_BUS			INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOMBRE			VARCHAR(50),
    CANT_PASAJEROS	INTEGER	
);

CREATE TABLE VIAJE(
	ID_VIAJE		INTEGER PRIMARY KEY AUTO_INCREMENT,
    RUTA			INTEGER,
    PARADA_INICIAL	INTEGER,
    PARADA_FINAL	INTEGER,
    HORARIO			INTEGER,
    BUS				INTEGER
);

CREATE TABLE TARIFA(
	ID_TARIFA	INTEGER PRIMARY KEY AUTO_INCREMENT,
	TARIFA		INTEGER,
    INICIO 		DATE
);

CREATE TABLE RUTA(
	ID_RUTA	INTEGER PRIMARY KEY AUTO_INCREMENT,
	TARIFA	INTEGER
);

CREATE TABLE POSICION(
	ID_POS		INTEGER PRIMARY KEY AUTO_INCREMENT,
	LATITUD 	INTEGER,
    LONGITUD	INTEGER
);

DROP SCHEMA SMART_ROUTES;
SELECT * FROM parada_media;

ALTER TABLE PARADAMEDIA
  ADD CONSTRAINT FK_VIAJE
  FOREIGN KEY (VIAJE)
  REFERENCES VIAJE (ID_VIAJE);
  
ALTER TABLE PARADAMEDIA
  ADD CONSTRAINT FK_POSICION
  FOREIGN KEY (POSICION)
  REFERENCES POSICION (ID_POS);
  
ALTER TABLE PARADA
  ADD CONSTRAINT FK_POSICION2
  FOREIGN KEY (POSICION)
  REFERENCES POSICION (ID_POS);
  
ALTER TABLE VIAJE
  ADD CONSTRAINT FK_RUTA
  FOREIGN KEY (RUTA)
  REFERENCES RUTA (ID_RUTA);

ALTER TABLE VIAJE
  ADD CONSTRAINT FK_PARADA_INICIAL
  FOREIGN KEY (PARADA_INICIAL)
  REFERENCES PARADA (ID_PARADA);  

ALTER TABLE VIAJE
  ADD CONSTRAINT FK_PARADA_FINAL
  FOREIGN KEY (PARADA_FINAL)
  REFERENCES PARADA (ID_PARADA);
  
ALTER TABLE VIAJE
  ADD CONSTRAINT FK_HORARIO
  FOREIGN KEY (HORARIO)
  REFERENCES HORARIO (ID_HORARIO);
  
ALTER TABLE VIAJE
  ADD CONSTRAINT FK_BUS
  FOREIGN KEY (BUS)
  REFERENCES BUS (ID_BUS);
  
ALTER TABLE RUTA
  ADD CONSTRAINT FK_TARIFA
  FOREIGN KEY (TARIFA)
  REFERENCES TARIFA (ID_TARIFA);